{{- $name := include "Secret-eso.fullname" . }}
{{- $labels := include "Secret-eso.labels" . }}
{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{- $labels | nindent 4 }}
  name: {{ $name }}-{{ .target.name }}
spec:
  dataFrom:
    {{- toYaml .dataFrom | nindent 4 }}
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: {{ $name }}
  target:
    name: {{ $name }}-{{ .target.name }}
    template:
      type: {{ .target.template.type }}
      metadata:
        labels:
        {{- toYaml .target.template.metadata.labels | nindent 10 }}
        annotations:
        {{- toYaml .target.template.metadata.annotations | nindent 10 }}
{{- end }}
 