apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  labels:
    {{- include "Secret-eso.labels" . | nindent 4 }}
  name: {{ include "Secret-eso.fullname" . }}
spec:
  provider:
    {{- toYaml .Values.Store.provider | nindent 4 }}
